include("C:/Program Files/CMake/share/cmake-4.4/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[test_set]==]
  TEST_EXECUTABLE [==[C:/Users/Ilnur/Desktop/labor1/mp2-practice/AribzhanovIR/sln/bin/test_set.exe]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[C:/Users/Ilnur/Desktop/labor1/mp2-practice/AribzhanovIR/sln/test]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[test_set_TESTS]==]
  CTEST_FILE [==[C:/Users/Ilnur/Desktop/labor1/mp2-practice/AribzhanovIR/sln/test/test_set_e3b0c442_Debug_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[C:/Users/Ilnur/Desktop/labor1/mp2-practice/AribzhanovIR/sln/test]==]
)
